### ISSUE TITLE
2 deprecations in latest atom version

### ISSUE THREAD

**Issue by MaxKK** [imamathwiz/atom-hide-files#4]
Two issues, the plugin is also responsible for the core issue. 

atom core:
> ContextMenuManager::add has changed to take a single object as its argument. Please see https://atom.io/docs/api/latest/ContextMenuManager for more info.
> Called 2 times
> ContextMenuManager.add - /Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:59:18
> Package.activateResources - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:296:61
> <unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:199:21
> Package.measure - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15

hide-files: 
> Store package style sheets in the styles/ directory instead of stylesheets/ in the hide-files package
> Called 1 timeCreate Issue on hide-files repo
> Package.getStylesheetsPath - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:430:9
> Package.getStylesheetPaths - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:441:32
> Package.loadStylesheets - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:423:38
> <unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:19

**Comment by imamathwiz** [comment]
Fixed with 60cd503b and 539f1adc

Thanks!
